#!/bin/bash
#
# @file       daily-snapshot
# @author     Chirantan Ekbote (chirantan.ekbote <at> gmail.com)
# @date       2012-11-01
# @version    0.4
# @brief      Script to generate a daily snapshot of the system using tarsnap
#
# ----------------------------------------------------------------------

unset PATH  # suggestion from H. Milz: avoid accidental use of $PATH

# ------------- system commands used by this script --------------------

DATE=/usr/bin/date
TARSNAP=/usr/bin/tarsnap
COMM=/usr/bin/comm
ECHO=/usr/bin/echo
SED=/usr/bin/sed
SORT=/usr/bin/sort
TAIL=/usr/bin/tail
GREP=/usr/bin/grep

# ------------- file locations and snapshot frequency ------------------

SOURCE_DIR=/
FREQUENCY=daily

# ------------- the script itself --------------------------------------

# Get the current time. We will use this as the name of the backup folder
TIME=$($DATE +%Y%m%d%H%M%S)

# Get the list of daily archives
ARCHIVES=$($TARSNAP --list-archives | $GREP $FREQUENCY | $SED \
    "s/${FREQUENCY}-//" | $SORT)

# Get the list of archives older than 6 days
TMPIFS=$IFS
IFS=' '
OLD_ARCHIVES=$($COMM -23 <($ECHO $ARCHIVES) <($ECHO $ARCHIVES | $TAIL -n 6))
IFS=$TMPIFS

# Remove all old archives
for a in $($ECHO $OLD_ARCHIVES); do
    $TARSNAP -df ${FREQUENCY}-$a --quiet --no-print-stats
done

# Create the new archive
$TARSNAP -cf ${FREQUENCY}-$TIME --quiet --no-print-stats $SOURCE_DIR
